default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: live_sound_development

test:
  <<: *default
  database: live_sound_test

production:
  <<: *default
  database: live_sound_production
